### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by midsmr** [showzeng/Minimalism#4]
本人从事PHP开发，对ruby不了解
GitHubWiki中提到安装需要用到`gem install`或 `bundle install`安装插件
由于本人本地没有ruby环境
又因为本人没有执行安装命令并成功运行
所以我像请问一下不执行安装命令会导致什么后果

**Comment by ZoeyWoohoo** [comment]
@midsmr 你好，Jekyll 框架是基于 Ruby 的，你不安装的话是没法玩的哈！你可以参照官方文档，先安装好 Ruby 环境 [Jekyll Docs](https://jekyllrb.com/docs/)。

**Comment by midsmr** [comment]
好的谢谢
